### ISSUE TITLE
File Permissions

### ISSUE THREAD

**Issue by rhnvrm** [Vutsuak16/filestats#1]
This could be a useful enhancement. In two modes, text: `r-w`, number: `777`

**Comment by Vutsuak16** [comment]
Permissions added
os.access(path,os.R_OK)

**Comment by Vutsuak16** [comment]
Well I put three permission checks:
 print "READABILITY: " + str(os.access(path, os.R_OK))
  print "WRITABILITY: " + str(os.access(path, os.W_OK))
  print "EXECUTION: " + str(os.access(path, os.X_OK))
